<a href="https://www.kaggle.com/code/riteshkumarweb/decision-tree-for-regression?scriptVersionId=317744336" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/abhishek14398/salary-dataset-simple-linear-regression/Salary_dataset.csv

In [2]:
# 🌳 Decision Tree Regressor

# DecisionTreeRegressor is a Supervised ML algorithm
# used for Regression problems

# 🎯 Goal:
# Predict continuous values
# Example:
# House Price 🏠
# Salary 💰
# Temperature 🌡️

# 🧠 It works by splitting data into smaller groups
# based on feature conditions

# Example:
# Is area > 1000 ?
# ├── Yes → Higher price
# └── No  → Lower price

# Instead of predicting classes,
# it predicts numerical values


# 📦 Import DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor


# 🧠 Create the model
model = DecisionTreeRegressor(

    max_depth=5,
    # 🌲 Maximum depth of tree
    # Controls complexity

    min_samples_split=4,
    # ✂️ Minimum samples needed to split a node

    min_samples_leaf=2,
    # 🍃 Minimum samples required in a leaf node
)

# 📊 Important:
# Decision Tree Regressor creates step-like predictions
# instead of smooth linear lines

# ⚠️ Can easily overfit if tree becomes very deep

In [3]:
df = pd.read_csv('/kaggle/input/datasets/abhishek14398/salary-dataset-simple-linear-regression/Salary_dataset.csv')

In [4]:
df

    Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [5]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [6]:
df

    YearsExperience    Salary
0               1.2   39344.0
1               1.4   46206.0
2               1.6   37732.0
3               2.1   43526.0
4               2.3   39892.0
5               3.0   56643.0
6               3.1   60151.0
7               3.3   54446.0
8               3.3   64446.0
9               3.8   57190.0
10              4.0   63219.0
11              4.1   55795.0
12              4.1   56958.0
13              4.2   57082.0
14              4.6   61112.0
15              5.0   67939.0
16              5.2   66030.0
17              5.4   83089.0
18              6.0   81364.0
19              6.1   93941.0
20              6.9   91739.0
21              7.2   98274.0
22              8.0  101303.0
23              8.3  113813.0
24              8.8  109432.0
25              9.1  105583.0
26              9.6  116970.0
27              9.7  112636.0
28             10.4  122392.0
29             10.6  121873.0

In [7]:
X = df[['YearsExperience']]
#X = df.iloc[:,0]
y = df.iloc[:,1]

In [8]:
X.shape

(30, 1)

In [9]:
y.shape

(30,)

In [10]:
from sklearn.model_selection import train_test_split


from sklearn.metrics import r2_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2,  random_state=42 )

In [11]:
X_test

    YearsExperience
27              9.7
15              5.0
23              8.3
17              5.4
8               3.3
9               3.8

In [12]:
from sklearn.linear_model import LinearRegression#First I tried with LR
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred = model.predict(X_test)

In [14]:
from sklearn.metrics import r2_score
score = r2_score(y_test,y_pred)
score

0.9024461774180497

In [15]:
from sklearn.tree import DecisionTreeRegressor#Then with the DesionTreeRegressor
model = DecisionTreeRegressor(max_depth=5)
model.fit(X_train,y_train)
y_pred_D = model.predict(X_test)

In [16]:
from sklearn.metrics import r2_score
score = r2_score(y_test,y_pred_D)
print(f'The Score of this Dataset is {score*100:.2f} % for the DecisionTreeRegressor')

The Score of this Dataset is 83.49 % for the DecisionTreeRegressor