<a href="https://www.kaggle.com/code/riteshkumarweb/gradient-boosting-regression?scriptVersionId=321343709" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/riteshkumarweb/student-marks/Student_Marks.csv

In [ ]:
# ⚡ Gradient Boosting Regressor

# GradientBoostingRegressor is an Ensemble Learning algorithm
# used for Regression problems

# 🎯 Goal:
# Predict continuous numerical values

# Example:
# House Price 🏠
# Salary 💰
# Temperature 🌡️

# 🧠 Idea:
# Train models sequentially
# where each new model tries to fix
# errors made by previous models

# 📦 Uses:
# Small Decision Trees as weak learners


# 🔁 Working:

# Step 1️⃣
# Train first Decision Tree

# Step 2️⃣
# Calculate Residuals (Errors)

# Residual = Actual - Predicted

# Step 3️⃣
# Train next tree on residuals/errors

# Step 4️⃣
# Add predictions from new tree
# to improve previous prediction

# Step 5️⃣
# Repeat sequentially many times


# 📊 Final Prediction:
# Sum of predictions from all trees


# 📦 Important Hyperparameters:

# n_estimators
# → Number of trees/weak learners

# learning_rate
# → Contribution of each tree

# Small learning_rate:
# → Slower learning
# → Better generalization

# Large learning_rate:
# → Faster learning
# → Risk of overfitting

# max_depth
# → Maximum depth of each tree

# subsample
# → Fraction of samples used
# for training each tree

# loss
# → Loss function used for optimization

# random_state
# → Ensures reproducible results


# 📊 GradientBoostingRegressor Example

from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(

    n_estimators=100,
    # 🌳 Number of trees

    learning_rate=0.1,
    # ⚡ Contribution of each tree

    max_depth=3,
    # 🌲 Maximum tree depth

    random_state=42
    # 🔁 Reproducible results
)


# ✅ Advantages:
# High prediction accuracy
# Handles non-linear data
# Reduces bias and variance
# Strong performance on tabular data

# ❌ Disadvantages:
# Slow training
# Sensitive to hyperparameters
# Can overfit if trees are too deep


# 📊 Simple Diagram:

#          📥 Original Dataset
#                   │
#              🌳 Tree1
#                   │
#            ❌ Residuals
#                   │
#              🌳 Tree2
#                   │
#            ❌ Residuals
#                   │
#              🌳 Tree3
#                   │
#         ➕ Add Predictions
#                   │
#            ✅ Final Output

In [3]:
df = pd.read_csv('/kaggle/input/datasets/riteshkumarweb/student-marks/Student_Marks.csv')

In [4]:
df

    number_courses  time_study   Marks
0                3       4.508  19.202
1                4       0.096   7.734
2                4       3.133  13.811
3                6       7.909  53.018
4                8       7.811  55.299
..             ...         ...     ...
95               6       3.561  19.128
96               3       0.301   5.609
97               4       7.163  41.444
98               7       0.309  12.027
99               3       6.335  32.357

[100 rows x 3 columns]

In [5]:
X = df.iloc[:,0:2]
X

    number_courses  time_study
0                3       4.508
1                4       0.096
2                4       3.133
3                6       7.909
4                8       7.811
..             ...         ...
95               6       3.561
96               3       0.301
97               4       7.163
98               7       0.309
99               3       6.335

[100 rows x 2 columns]

In [7]:
y = df.iloc[:,2]
y

0     19.202
1      7.734
2     13.811
3     53.018
4     55.299
       ...
95    19.128
96     5.609
97    41.444
98    12.027
99    32.357
Name: Marks, Length: 100, dtype: float64

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
X_train

    number_courses  time_study
55               7       2.913
88               5       1.803
26               7       0.508
42               6       3.591
69               6       3.948
..             ...         ...
60               6       0.376
71               5       2.518
14               3       2.908
92               4       5.027
51               6       4.130

[80 rows x 2 columns]

# Appling Linear Regression to this Student Marks Dataset ¶

In [16]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
print('The accuracy for this model is this',r2_score(y_test,y_pred) )

scores = cross_val_score(lr, X, y, cv=10, scoring='r2')
print(f'The Cross_val_score and mean r2_score of this dataset is: {np.mean(scores):.2f}')

The accuracy for this model is this 0.9459936100591213
The Cross_val_score and mean r2_score of this dataset is: 0.87

# Applying Grading Boosting to this Student Marks dataset

In [17]:
from sklearn.ensemble import GradientBoostingRegressor
gd = GradientBoostingRegressor(learning_rate=0.1,n_estimators=1000,)

gd.fit(X_train,y_train)
y_pred_gd = gd.predict(X_test)
print('The accuracy for Grading Boosting model is this',r2_score(y_test,y_pred_gd) )

scores_gd = cross_val_score(gd, X, y, cv=10, scoring='r2')
print(f'The Cross_val_score and mean r2_score of this dataset on Gradient : {np.mean(scores_gd)}')

The accuracy for Grading Boosting model is this 0.9962126462315353
The Cross_val_score and mean r2_score of this dataset on Gradient : 0.9886572055707378

 # Appling GridSearchCV on Gradient Boosting Regressor to search best_score and best_params for Student Marks Dataset

In [28]:
loss= ['squared_error','absolute_error']
learning_rate = [0.1,0.001]
n_estimators = [100,500 ]
criterion = ['friedman_mse', 'squared_error']
max_depth = [8,32]
params = {'loss':loss,'learning_rate':learning_rate,'n_estimators':n_estimators,'criterion':criterion,'max_depth':max_depth}
print(params)
from sklearn.model_selection import GridSearchCV
search_gd = GradientBoostingRegressor()
search = GridSearchCV(search_gd, params,scoring='r2',n_jobs= -1)
search.fit(X_train,y_train)

{'loss': ['squared_error', 'absolute_error'], 'learning_rate': [0.1, 0.001], 'n_estimators': [100, 500], 'criterion': ['friedman_mse', 'squared_error'], 'max_depth': [8, 32]}

GridSearchCV(estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'learning_rate': [0.1, 0.001],
                         'loss': ['squared_error', 'absolute_error'],
                         'max_depth': [8, 32], 'n_estimators': [100, 500]},
             scoring='r2')

In [22]:
print(search.best_score_)

0.9889425894504896

In [23]:
print(search.best_params_)

{'criterion': 'squared_error', 'learning_rate': 0.1, 'loss': 'absolute_error', 'max_depth': 32, 'n_estimators': 500}

In [27]:
test_score = search.score(X_test, y_test)
print(f"Test Set Score: {test_score}")

Test Set Score: 0.9932447812828065

In [ ]:
#test_score = grid_search.score(X_test, y_test)
#What it does internally:
#python
#def score(self, X_test, y_test):
    #y_pred = self.predict(X_test)           # Step 1: Make predictions
   # accuracy = accuracy_score(y_test, y_pred)  # Step 2: Compare with true labels
    #return accuracy